# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('CryptoCurrency_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CryptoCurrency_Name', models.CharField(max_length=200)),
                ('CryptoCurrency_Number_of_Tokens', models.CharField(max_length=200)),
                ('CryptoCurrency_Purchase_Price', models.CharField(max_length=200)),
                ('CryptoCurrency_Purchase_Date', models.CharField(max_length=200)),
                ('CryptoCurrency_Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('CryptoCurrency_Modified_Date', models.DateTimeField(blank=True, null=True)),
                ('CryptoCurrency_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('customer_Name', models.CharField(max_length=200)),
                ('customer_StreetAddress', models.CharField(max_length=200)),
                ('customer_City', models.CharField(max_length=200)),
                ('customer_State', models.CharField(max_length=200)),
                ('customer_ZIP', models.CharField(max_length=200)),
                ('customer_Email', models.CharField(max_length=200)),
                ('customer_Phone', models.CharField(max_length=200)),
                ('customer_Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_Modified_Date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_ID', models.AutoField(primary_key=True, serialize=False)),
                ('stock_Symbol', models.CharField(max_length=200)),
                ('stock_Name', models.CharField(max_length=200)),
                ('stock_Number_of_Shares', models.CharField(max_length=200)),
                ('stock_Purchase_Price', models.CharField(max_length=200)),
                ('stock_Purchase_Date', models.CharField(max_length=200)),
                ('stock_Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_Modified_Date', models.DateTimeField(blank=True, null=True)),
                ('stock_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
